import type { NavigationLink, Disease } from './types';

export const NAV_LINKS: NavigationLink[] = [
  { name: 'navHome', path: '/' },
  { name: 'navDiagnostics', path: '/diagnostics-playground' },
  { name: 'navDatabase', path: '/disease-database' },
  { name: 'navPrevention', path: '/prevention' },
  { name: 'navVisualLibrary', path: '/visual-library' },
  { name: 'navBreeds', path: '/breeds' },
  { name: 'navResources', path: '/resources' },
  { name: 'navAboutUs', path: '/about-us' },
];

export const DISEASES_DATA: Disease[] = [
    {
        id: 1,
        name: 'Newcastle Disease (ND)',
        name_fr: 'Maladie de Newcastle (MN)',
        aliases: ['Avian Paramyxovirus-1 (APMV-1)', 'Fowl Pest'],
        aliases_fr: ['Paramyxovirose aviaire-1 (APMV-1)', 'Peste aviaire'],
        scientificName: 'Avian orthoavulavirus 1',
        description: 'A highly contagious, notifiable viral disease with high mortality in unvaccinated flocks. A major constraint in Moroccan poultry production.',
        description_fr: "Une maladie virale très contagieuse et à déclaration obligatoire, avec une mortalité élevée dans les troupeaux non vaccinés. Une contrainte majeure dans la production avicole marocaine.",
        etiology: 'Viral',
        urgency: 'HIGH',
        isNotifiableInMorocco: true,
        speciesAffected: ['Chickens', 'Turkeys', 'Ducks', 'Geese'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Canards', 'Oies'],
        transmission: 'Airborne, contaminated equipment, wild birds, feces, people',
        transmission_fr: 'Aéroportée, équipement contaminé, oiseaux sauvages, fèces, personnes',
        symptoms: ['Respiratory distress', 'Gasping', 'Coughing', 'Nervous signs (tremors, paralysis, twisted neck)', 'Green diarrhea', 'Sudden death', 'Reduced egg production'],
        symptoms_fr: ['Détresse respiratoire', 'Halètement', 'Toux', 'Signes nerveux (tremblements, paralysie, torticolis)', 'Diarrhée verdâtre', 'Mort subite', 'Baisse de ponte'],
        lesionsAtNecropsy: ['Hemorrhages in proventriculus', 'Hemorrhages in intestines', 'Hemorrhages in cecal tonsils', 'Tracheitis', 'Lung congestion'],
        lesionsAtNecropsy_fr: ['Hémorragies dans le proventricule', 'Hémorragies dans les intestins', 'Hémorragies sur les amygdales cæcales', 'Trachéite', 'Congestion pulmonaire'],
        bodySystemAffected: ['Respiratory', 'Nervous', 'Systemic'],
        bodySystemAffected_fr: ['Respiratoire', 'Nerveux', 'Systémique'],
        treatment: 'Supportive care only; no specific antiviral',
        treatment_fr: "Soins de soutien uniquement ; pas d'antiviral spécifique",
        prevention: 'Vaccination (LaSota, I-2, inactivated), biosecurity, quarantine',
        prevention_fr: 'Vaccination (LaSota, I-2, inactivée), biosécurité, quarantaine',
        differentialDiagnosis: ['Avian influenza', 'Infectious laryngotracheitis', 'Mycoplasmosis'],
        differentialDiagnosis_fr: ['Grippe aviaire', 'Laryngotrachéite infectieuse', 'Mycoplasmose'],
        region: 'Morocco, Global',
        moroccoNote: 'Endemic; vaccination mandatory in commercial flocks. Backyard outbreaks common.',
        moroccoNote_fr: "Endémique ; vaccination obligatoire dans les élevages commerciaux. Foyers fréquents dans les basses-cours.",
        references: [
            { text: 'WOAH – Newcastle Disease', url: 'https://www.woah.org/en/disease/newcastle-disease/' },
            { text: 'FAO EMPRES-i Outbreak Database (Morocco reports)', url: 'https://empres-i.apps.fao.org/' },
            { text: 'Ministry of Agriculture, Morocco – Animal Health Directorate', url: 'https://www.agriculture.gov.ma/' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 2,
        name: 'Avian Influenza (HPAI)',
        name_fr: 'Influenza Aviaire (HPAI)',
        aliases: ['Bird Flu (H5N1, H5N8)'],
        aliases_fr: ['Grippe aviaire (H5N1, H5N8)'],
        scientificName: 'Influenza A virus (H5/H7 subtypes)',
        description: 'A zoonotic, notifiable disease with high mortality in chickens. Wild birds are key reservoirs. Requires immediate reporting.',
        description_fr: "Une maladie zoonotique à déclaration obligatoire avec une mortalité élevée chez les poulets. Les oiseaux sauvages sont les principaux réservoirs. Nécessite une déclaration immédiate.",
        etiology: 'Viral',
        urgency: 'HIGH',
        zoonoticRisk: 'HIGH',
        isNotifiableInMorocco: true,
        speciesAffected: ['Chickens', 'Turkeys', 'Ducks', 'Geese'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Canards', 'Oies'],
        transmission: 'Wild birds (especially waterfowl), contaminated equipment, people, vehicles',
        transmission_fr: "Oiseaux sauvages (en particulier les oiseaux d'eau), équipement contaminé, personnes, véhicules",
        symptoms: ['Sudden death', 'Swollen head, cyanotic comb', 'Respiratory distress', 'Reduced egg production', 'Diarrhea'],
        symptoms_fr: ['Mort subite', 'Tête enflée, crête cyanosée', 'Détresse respiratoire', 'Baisse de ponte', 'Diarrhée'],
        lesionsAtNecropsy: ['Edema of head', 'Edema of neck', 'Hemorrhages in legs', 'Hemorrhages in internal organs', 'Pancreatic necrosis'],
        lesionsAtNecropsy_fr: ['Œdème de la tête', 'Œdème du cou', 'Hémorragies sur les pattes', 'Hémorragies sur les organes internes', 'Nécrose pancréatique'],
        bodySystemAffected: ['Respiratory', 'Systemic'],
        bodySystemAffected_fr: ['Respiratoire', 'Systémique'],
        treatment: 'None. Mandatory culling required',
        treatment_fr: "Aucun. Abattage sanitaire obligatoire.",
        prevention: 'Biosecurity, surveillance, movement control, rapid reporting',
        prevention_fr: 'Biosécurité, surveillance, contrôle des mouvements, déclaration rapide',
        differentialDiagnosis: ['Newcastle disease', 'Fowl cholera', 'Infectious bronchitis'],
        differentialDiagnosis_fr: ['Maladie de Newcastle', 'Choléra aviaire', 'Bronchite infectieuse'],
        region: 'Morocco, Global',
        moroccoNote: 'H5N1 outbreaks reported; surveillance active by Ministry of Agriculture.',
        moroccoNote_fr: "Foyers de H5N1 signalés ; surveillance active par le Ministère de l'Agriculture.",
        references: [
            { text: 'WOAH – Avian Influenza', url: 'https://www.woah.org/en/disease/avian-influenza/' },
            { text: 'FAO EMPRES-i Outbreak Database (Morocco reports)', url: 'https://empres-i.apps.fao.org/' },
            { text: 'Ministry of Agriculture, Morocco – Animal Health Directorate', url: 'https://www.agriculture.gov.ma/' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 3,
        name: 'Infectious Bronchitis (IB)',
        name_fr: 'Bronchite Infectieuse (BI)',
        aliases: ['IBV'],
        aliases_fr: ['VBI'],
        scientificName: 'Avian coronavirus (IBV)',
        description: 'A rapidly spreading respiratory virus that can cause permanent oviduct damage in pullets, reducing egg production.',
        description_fr: "Un virus respiratoire à propagation rapide qui peut causer des dommages permanents à l'oviducte chez les poulettes, réduisant la production d'œufs.",
        etiology: 'Viral',
        urgency: 'MEDIUM',
        speciesAffected: ['Chickens'],
        speciesAffected_fr: ['Poulets'],
        transmission: 'Airborne, contaminated equipment, people',
        transmission_fr: 'Aéroportée, équipement contaminé, personnes',
        symptoms: ['Sneezing, tracheal rales', 'Coughing', 'Reduced egg production', 'Misshapen/soft-shelled eggs'],
        symptoms_fr: ['Éternuements, râles trachéaux', 'Toux', 'Baisse de ponte', 'Œufs déformés/à coquille molle'],
        lesionsAtNecropsy: ['Mucus in trachea', 'Caseous plugs in bronchi', 'Oviduct damage'],
        lesionsAtNecropsy_fr: ['Mucus dans la trachée', 'Bouchons caséeux dans les bronches', "Lésions de l'oviducte"],
        bodySystemAffected: ['Respiratory', 'Reproductive'],
        bodySystemAffected_fr: ['Respiratoire', 'Reproducteur'],
        treatment: 'Supportive care; antibiotics for secondary infections',
        treatment_fr: 'Soins de soutien ; antibiotiques pour les infections secondaires',
        prevention: 'Live (H120, Ma5) and inactivated vaccines, all-in/all-out',
        prevention_fr: 'Vaccins vivants (H120, Ma5) et inactivés, conduite en bande unique',
        differentialDiagnosis: ['Mycoplasmosis', 'ILT', 'Newcastle disease'],
        differentialDiagnosis_fr: ['Mycoplasmose', 'LTI', 'Maladie de Newcastle'],
        region: 'Morocco, Global',
        moroccoNote: 'Multiple strains circulate; vaccine mismatch is a common issue.',
        moroccoNote_fr: "Plusieurs souches circulent ; l'inadéquation vaccinale est un problème courant.",
        references: [
            { text: 'FAO IB Guide', url: 'https://www.fao.org/poultry-production-and-products/en/' },
            { text: 'Avian Pathology, 2020', url: 'https://scholar.google.com/scholar?q=Avian+Pathology+Infectious+Bronchitis+2020' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 4,
        name: 'Infectious Bursal Disease (IBD) – Gumboro',
        name_fr: 'Maladie de Gumboro (MBI)',
        aliases: ['Gumboro Disease'],
        aliases_fr: ['Bursite infectieuse'],
        scientificName: 'Avibirnavirus',
        description: 'A viral disease destroying the bursa of Fabricius, causing immunosuppression and increased susceptibility to other diseases.',
        description_fr: "Une maladie virale qui détruit la bourse de Fabricius, provoquant une immunosuppression et une sensibilité accrue à d'autres maladies.",
        etiology: 'Viral',
        urgency: 'HIGH',
        speciesAffected: ['Chickens'],
        speciesAffected_fr: ['Poulets'],
        transmission: 'Fecal-oral, contaminated litter, equipment, people',
        transmission_fr: 'Féco-orale, litière contaminée, équipement, personnes',
        symptoms: ['Depression, ruffled feathers', 'White watery diarrhea', 'Dehydration', 'Immunosuppression'],
        symptoms_fr: ['Dépression, plumes hérissées', 'Diarrhée blanche aqueuse', 'Déshydratation', 'Immunosuppression'],
        lesionsAtNecropsy: ['Swollen bursa', 'Hemorrhagic bursa', 'Atrophied bursa', 'Muscular hemorrhages'],
        lesionsAtNecropsy_fr: ['Bourse de Fabricius enflée', 'Bourse hémorragique', 'Bourse atrophiée', 'Hémorragies musculaires'],
        bodySystemAffected: ['Immune', 'Digestive'],
        bodySystemAffected_fr: ['Immunitaire', 'Digestif'],
        treatment: 'None; high mortality in acute cases',
        treatment_fr: "Aucun ; mortalité élevée dans les cas aigus",
        prevention: 'Maternal vaccination, live/inactivated vaccines, hygiene',
        prevention_fr: 'Vaccination des reproductrices, vaccins vivants/inactivés, hygiène',
        differentialDiagnosis: ['Coccidiosis', 'Marek’s disease', 'vitamin K deficiency'],
        differentialDiagnosis_fr: ['Coccidiose', 'Maladie de Marek', 'carence en vitamine K'],
        region: 'Morocco, Global',
        moroccoNote: 'Widespread in broiler farms; leads to secondary infections due to immunosuppression.',
        moroccoNote_fr: "Répandue dans les élevages de poulets de chair ; entraîne des infections secondaires dues à l'immunosuppression.",
        references: [{ text: 'WOAH IBD', url: 'https://www.woah.org/en/disease/infectious-bursal-disease-gumboro-disease/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 5,
        name: 'Mycoplasmosis (Mycoplasma gallisepticum)',
        name_fr: 'Mycoplasmose (Mycoplasma gallisepticum)',
        aliases: ['Chronic Respiratory Disease (CRD)'],
        aliases_fr: ['Maladie Respiratoire Chronique (MRC)'],
        scientificName: 'Mycoplasma gallisepticum',
        description: 'A chronic respiratory disease that worsens with stress or poor air quality. Causes significant economic losses.',
        description_fr: "Une maladie respiratoire chronique qui s'aggrave avec le stress ou une mauvaise qualité de l'air. Provoque des pertes économiques importantes.",
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        speciesAffected: ['Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets', 'Dindes'],
        transmission: 'Vertical (eggs), aerosol, contaminated equipment',
        transmission_fr: 'Verticale (œufs), aérosol, équipement contaminé',
        symptoms: ['Nasal discharge', 'Coughing, sneezing', 'Swollen sinuses', 'Reduced growth', 'Reduced egg production'],
        symptoms_fr: ['Écoulement nasal', 'Toux, éternuements', 'Sinus enflés', 'Croissance réduite', 'Baisse de ponte'],
        lesionsAtNecropsy: ['Sinusitis with caseous exudate', 'Thickened air sacs', 'Cloudy air sacs', 'Tracheitis'],
        lesionsAtNecropsy_fr: ['Sinusite avec exsudat caséeux', 'Sacs aériens épaissis', 'Sacs aériens opaques', 'Trachéite'],
        bodySystemAffected: ['Respiratory'],
        bodySystemAffected_fr: ['Respiratoire'],
        treatment: 'Tylosin, tetracyclines, tilmicosin (veterinary prescription)',
        treatment_fr: 'Tylosine, tétracyclines, tilmicosine (prescription vétérinaire)',
        prevention: 'Clean hatcheries, biosecurity, vaccination (F-strain, inactivated)',
        prevention_fr: 'Propreté des couvoirs, biosécurité, vaccination (souche F, inactivée)',
        differentialDiagnosis: ['Infectious bronchitis', 'ILT', 'fowl cholera'],
        differentialDiagnosis_fr: ['Bronchite infectieuse', 'LTI', 'choléra aviaire'],
        region: 'Morocco, Global',
        moroccoNote: 'Common in poorly ventilated or overcrowded farms.',
        moroccoNote_fr: 'Fréquente dans les élevages mal ventilés ou surpeuplés.',
        references: [
            { text: 'USDA MG Guide', url: 'https://www.aphis.usda.gov/animal_health/animal_diseases/npep/downloads/mg-ls-pamphlet.pdf' },
            { text: 'Poultry Science, 2019', url: 'https://scholar.google.com/scholar?q=Poultry+Science+Mycoplasma+gallisepticum+2019' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 6,
        name: 'Coccidiosis',
        name_fr: 'Coccidiose',
        aliases: ['Eimeria infection'],
        aliases_fr: ['Infection à Eimeria'],
        scientificName: 'Eimeria spp. (E. tenella, E. acervulina, etc.)',
        description: 'A parasitic gut disease causing bloody diarrhea and poor performance. Preventable with good management.',
        description_fr: "Une maladie intestinale parasitaire provoquant des diarrhées sanglantes et de mauvaises performances. Évitable avec une bonne gestion.",
        etiology: 'Parasitic',
        urgency: 'HIGH',
        speciesAffected: ['Chickens', 'Turkeys', 'Ducks'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Canards'],
        transmission: 'Fecal-oral, wet litter, contaminated equipment',
        transmission_fr: 'Féco-orale, litière humide, équipement contaminé',
        symptoms: ['Bloody diarrhea', 'Weight loss', 'Anemia', 'Huddling, ruffled feathers', 'High chick mortality'],
        symptoms_fr: ['Diarrhée sanglante', 'Perte de poids', 'Anémie', 'Prostration, plumes hérissées', 'Mortalité élevée des poussins'],
        lesionsAtNecropsy: ['Hemorrhagic ceca with cores', 'Whitish spots in small intestine'],
        lesionsAtNecropsy_fr: ['Caeca hémorragiques avec cylindres caséeux', 'Points blanchâtres sur l’intestin grêle'],
        bodySystemAffected: ['Digestive'],
        bodySystemAffected_fr: ['Digestif'],
        treatment: 'Amprolium, sulfonamides, toltrazuril',
        treatment_fr: 'Amprolium, sulfamides, toltrazuril',
        prevention: 'Dry litter, anticoccidial feed additives, rotation, vaccination (broilers)',
        prevention_fr: 'Litière sèche, additifs alimentaires anticoccidiens, rotation, vaccination (poulets de chair)',
        differentialDiagnosis: ['Histomoniasis', 'salmonellosis', 'necrotic enteritis'],
        differentialDiagnosis_fr: ['Histomonose', 'salmonellose', 'entérite nécrotique'],
        region: 'Morocco, Global',
        moroccoNote: 'High risk in humid seasons and backyard flocks.',
        moroccoNote_fr: 'Risque élevé pendant les saisons humides et dans les élevages de basse-cour.',
        references: [
            { text: 'FAO Coccidiosis Manual', url: 'https://www.fao.org/documents/card/en/c/ca7537en' },
            { text: 'Veterinary Parasitology, 2021', url: 'https://scholar.google.com/scholar?q=Veterinary+Parasitology+coccidiosis+poultry+2021' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 7,
        name: 'Infectious Laryngotracheitis (ILT)',
        name_fr: 'Laryngotrachéite Infectieuse (LTI)',
        aliases: ['ILTV'],
        aliases_fr: ['VLT'],
        scientificName: 'Gallid alphaherpesvirus 1',
        description: 'A herpesvirus causing severe upper respiratory disease with high mortality. Vaccination can cause spread.',
        description_fr: "Un herpèsvirus provoquant une maladie respiratoire supérieure sévère avec une mortalité élevée. La vaccination peut propager la maladie.",
        etiology: 'Viral',
        urgency: 'HIGH',
        isNotifiableInMorocco: true,
        speciesAffected: ['Chickens', 'Pheasants'],
        speciesAffected_fr: ['Poulets', 'Faisans'],
        transmission: 'Aerosol, contaminated equipment, latent carriers',
        transmission_fr: 'Aérosol, équipement contaminé, porteurs latents',
        symptoms: ['Severe respiratory distress', 'Gasping, coughing up blood', 'Nasal discharge', 'High mortality'],
        symptoms_fr: ['Détresse respiratoire sévère', 'Halètement, toux avec sang', 'Écoulement nasal', 'Mortalité élevée'],
        lesionsAtNecropsy: ['Hemorrhagic trachea', 'Blood clots in trachea', 'Diphtheritic membranes in upper trachea'],
        lesionsAtNecropsy_fr: ['Trachée hémorragique', 'Caillots de sang dans la trachée', 'Membranes diphtériques dans la trachée supérieure'],
        bodySystemAffected: ['Respiratory'],
        bodySystemAffected_fr: ['Respiratoire'],
        treatment: 'Supportive care, antibiotics for secondary infections',
        treatment_fr: 'Soins de soutien, antibiotiques pour les infections secondaires',
        prevention: 'Vaccination (live), biosecurity, avoid carrier birds',
        prevention_fr: 'Vaccination (vivant), biosécurité, éviter les oiseaux porteurs',
        differentialDiagnosis: ['Newcastle disease', 'IB', 'mycoplasmosis'],
        differentialDiagnosis_fr: ['Maladie de Newcastle', 'BI', 'mycoplasmose'],
        region: 'Morocco, Global',
        moroccoNote: 'Occasional outbreaks in dense layer farms.',
        moroccoNote_fr: 'Foyers occasionnels dans les élevages de pondeuses à forte densité.',
        references: [{ text: 'WOAH ILT', url: 'https://www.woah.org/en/disease/infectious-laryngotracheitis/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 8,
        name: 'Duck Virus Enteritis (DVE)',
        name_fr: 'Entérite Virale du Canard (EVC)',
        aliases: ['Duck Plague'],
        aliases_fr: ['Peste du canard'],
        scientificName: 'Anatid alphaherpesvirus 1',
        description: 'A fatal herpesvirus infection in waterfowl. Rapid spread in dense flocks.',
        description_fr: "Une infection herpétique mortelle chez les oiseaux d'eau. Propagation rapide dans les troupeaux denses.",
        etiology: 'Viral',
        urgency: 'HIGH',
        speciesAffected: ['Ducks', 'Geese', 'Swans'],
        speciesAffected_fr: ['Canards', 'Oies', 'Cygnes'],
        transmission: 'Contaminated water, direct contact',
        transmission_fr: 'Eau contaminée, contact direct',
        symptoms: ['Sudden death', 'Bloody diarrhea', 'Neck retraction', 'Hemorrhages on skin'],
        symptoms_fr: ['Mort subite', 'Diarrhée sanglante', 'Rétraction du cou', 'Hémorragies cutanées'],
        lesionsAtNecropsy: ['Liver necrosis', 'Hemorrhages on liver', 'Esophageal ulcers', 'Blood in body cavities'],
        lesionsAtNecropsy_fr: ['Nécrose du foie', 'Hémorragies sur le foie', 'Ulcères œsophagiens', 'Sang dans les cavités corporelles'],
        bodySystemAffected: ['Digestive', 'Systemic'],
        bodySystemAffected_fr: ['Digestif', 'Systémique'],
        treatment: 'None',
        treatment_fr: 'Aucun',
        prevention: 'Vaccination (attenuated), isolate from wild waterfowl',
        prevention_fr: "Vaccination (atténuée), isoler des oiseaux d'eau sauvages",
        differentialDiagnosis: ['Avian cholera', 'botulism', 'HPAI'],
        differentialDiagnosis_fr: ['Choléra aviaire', 'botulisme', 'IAHP'],
        region: 'Morocco, Global',
        moroccoNote: 'Risk near wetlands or mixed duck/geese farms.',
        moroccoNote_fr: 'Risque près des zones humides ou des fermes mixtes de canards/oies.',
        references: [{ text: 'FAO DVE Report', url: 'https://www.fao.org/documents/card/en/c/a0058e' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 9,
        name: 'Fowl Cholera',
        name_fr: 'Choléra Aviaire',
        aliases: ['Pasteurella multocida infection'],
        aliases_fr: ['Infection à Pasteurella multocida'],
        scientificName: 'Pasteurella multocida',
        description: 'A bacterial septicemia with high mortality. Often introduced by wildlife.',
        description_fr: "Une septicémie bactérienne à mortalité élevée. Souvent introduite par la faune sauvage.",
        etiology: 'Bacterial',
        urgency: 'HIGH',
        speciesAffected: ['Chickens', 'Turkeys', 'Ducks'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Canards'],
        transmission: 'Wild birds, rodents, wounds, contaminated water',
        transmission_fr: 'Oiseaux sauvages, rongeurs, blessures, eau contaminée',
        symptoms: ['Sudden death', 'Swollen wattles, joints', 'Green diarrhea'],
        symptoms_fr: ['Mort subite', 'Barbillon et articulations enflés', 'Diarrhée verdâtre'],
        lesionsAtNecropsy: ['Hemorrhages in organs', 'Caseous exudate in joints', 'Caseous exudate in sinuses', 'Enlarged liver', 'Necrotic liver'],
        lesionsAtNecropsy_fr: ['Hémorragies sur les organes', 'Exsudat caséeux dans les articulations', 'Exsudat caséeux dans les sinus', 'Foie hypertrophié', 'Foie nécrosé'],
        bodySystemAffected: ['Systemic'],
        bodySystemAffected_fr: ['Systémique'],
        treatment: 'Sulfonamides, tetracyclines (early)',
        treatment_fr: 'Sulfamides, tétracyclines (en début de maladie)',
        prevention: 'Vaccination, rodent control, biosecurity',
        prevention_fr: 'Vaccination, lutte contre les rongeurs, biosécurité',
        differentialDiagnosis: ['Fowl typhoid', 'salmonellosis', 'mycoplasmosis'],
        differentialDiagnosis_fr: ['Typhose aviaire', 'salmonellose', 'mycoplasmose'],
        region: 'Morocco, Global',
        moroccoNote: 'Sporadic in backyard flocks with poor rodent control.',
        moroccoNote_fr: 'Sporadique dans les basses-cours avec un mauvais contrôle des rongeurs.',
        references: [{ text: 'USDA Fowl Cholera', url: 'https://www.aphis.usda.gov/animal_health/animal_diseases/npep/downloads/fowl-cholera-pamphlet.pdf' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 10,
        name: "Egg Drop Syndrome '76 (EDS '76)",
        name_fr: "Syndrome de Chute de Ponte '76 (EDS '76)",
        aliases: ['Duck adenovirus B'],
        aliases_fr: ['Adénovirus B du canard'],
        scientificName: 'Avian adenovirus D',
        description: 'A viral disease causing sudden egg production drop and poor shell quality. Preventable with vaccination.',
        description_fr: "Une maladie virale provoquant une chute soudaine de la production d'œufs et une mauvaise qualité de coquille. Évitable par la vaccination.",
        etiology: 'Viral',
        urgency: 'MEDIUM',
        speciesAffected: ['Chickens', 'Pheasants'],
        speciesAffected_fr: ['Poulets', 'Faisans'],
        transmission: 'Contaminated egg trays, water, vertical transmission',
        transmission_fr: 'Plateaux à œufs contaminés, eau, transmission verticale',
        symptoms: ['Reduced egg production', 'Thin-shelled, shell-less eggs', 'Pale eggs'],
        symptoms_fr: ['Baisse de ponte', 'Œufs à coquille mince, sans coquille', 'Œufs pâles'],
        lesionsAtNecropsy: ['Oviduct inflammation'],
        lesionsAtNecropsy_fr: ["Inflammation de l'oviducte"],
        bodySystemAffected: ['Reproductive'],
        bodySystemAffected_fr: ['Reproducteur'],
        treatment: 'None',
        treatment_fr: 'Aucun',
        prevention: 'Vaccination, disinfect egg trays, source clean eggs',
        prevention_fr: 'Vaccination, désinfection des plateaux à œufs, approvisionnement en œufs sains',
        differentialDiagnosis: ['IB', 'mycoplasma', 'nutritional deficiency'],
        differentialDiagnosis_fr: ['BI', 'mycoplasme', 'carence nutritionnelle'],
        region: 'Morocco, Global',
        moroccoNote: 'Often misdiagnosed as IB or calcium deficiency.',
        moroccoNote_fr: 'Souvent mal diagnostiqué comme une BI ou une carence en calcium.',
        references: [{ text: "WOAH EDS '76", url: 'https://www.woah.org/en/disease/egg-drop-syndrome-76/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 11,
        name: 'Avian Encephalomyelitis (AE)',
        name_fr: 'Encéphalomyélite Aviaire (EA)',
        aliases: ['Epidemic Tremor'],
        aliases_fr: ['Tremblement épidémique'],
        scientificName: 'Avian encephalomyelitis virus',
        description: 'A viral disease of young chicks causing tremors and paralysis. Controlled by maternal vaccination.',
        description_fr: "Une maladie virale des jeunes poussins provoquant des tremblements et une paralysie. Contrôlée par la vaccination des reproductrices.",
        etiology: 'Viral',
        urgency: 'HIGH',
        speciesAffected: ['Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets', 'Dindes'],
        transmission: 'Vertical (eggs), fecal-oral',
        transmission_fr: 'Verticale (œufs), féco-orale',
        symptoms: ['Tremors, ataxia', 'Paralysis', 'High chick mortality'],
        symptoms_fr: ['Tremblements, ataxie', 'Paralysie', 'Mortalité élevée des poussins'],
        lesionsAtNecropsy: ['Neuronal degeneration'],
        lesionsAtNecropsy_fr: ['Dégénérescence neuronale'],
        bodySystemAffected: ['Nervous'],
        bodySystemAffected_fr: ['Nerveux'],
        treatment: 'None',
        treatment_fr: 'Aucun',
        prevention: 'Vaccinate breeder hens',
        prevention_fr: 'Vacciner les poules reproductrices',
        differentialDiagnosis: ['Marek’s', 'vitamin E/selenium deficiency'],
        differentialDiagnosis_fr: ['Maladie de Marek', 'carence en vitamine E/sélénium'],
        region: 'Morocco, Global',
        moroccoNote: 'Rare but severe if breeders are unvaccinated.',
        moroccoNote_fr: 'Rare mais grave si les reproducteurs ne sont pas vaccinés.',
        references: [{ text: 'Avian Diseases, 2018', url: 'https://scholar.google.com/scholar?q=Avian+Diseases+Avian+Encephalomyelitis+2018' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 12,
        name: 'Marek’s Disease',
        name_fr: 'Maladie de Marek',
        aliases: ['Avian Leukosis-Sarcoma Virus (ALSV)'],
        aliases_fr: ['Virus de la Leucose-Sarcome Aviaire (ALSV)'],
        scientificName: 'Gallid alphaherpesvirus 2',
        description: 'A herpesvirus causing tumors and paralysis. Controlled by day-old vaccination.',
        description_fr: "Un herpèsvirus provoquant des tumeurs et une paralysie. Contrôlé par la vaccination à l'âge d'un jour.",
        etiology: 'Viral',
        urgency: 'HIGH',
        speciesAffected: ['Chickens'],
        speciesAffected_fr: ['Poulets'],
        transmission: 'Airborne (feather dander), vertical (rare)',
        transmission_fr: 'Aéroportée (poussière de plumes), verticale (rare)',
        symptoms: ['Paralysis', 'Weight loss', 'Gray iris, blindness', 'Tumors'],
        symptoms_fr: ['Paralysie', 'Perte de poids', 'Iris gris, cécité', 'Tumeurs'],
        lesionsAtNecropsy: ['Tumors in liver', 'Tumors in spleen', 'Tumors in nerves', 'Enlarged peripheral nerves'],
        lesionsAtNecropsy_fr: ['Tumeurs au foie', 'Tumeurs à la rate', 'Tumeurs sur les nerfs', 'Nerfs périphériques hypertrophiés'],
        bodySystemAffected: ['Nervous', 'Immune', 'Systemic'],
        bodySystemAffected_fr: ['Nerveux', 'Immunitaire', 'Systémique'],
        treatment: 'None',
        treatment_fr: 'Aucun',
        prevention: 'Vaccinate day-old chicks, clean hatcheries',
        prevention_fr: 'Vacciner les poussins d’un jour, propreté des couvoirs',
        differentialDiagnosis: ['Lymphoid leukosis', 'ALV', 'vitamin deficiency'],
        differentialDiagnosis_fr: ['Leucose lymphoïde', 'VLA', 'carence vitaminique'],
        region: 'Morocco, Global',
        moroccoNote: 'Vaccination standard in commercial hatcheries.',
        moroccoNote_fr: 'La vaccination est la norme dans les couvoirs commerciaux.',
        references: [{ text: 'FAO Marek’s Guide', url: 'https://www.fao.org/documents/card/en/c/a-i3921e' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 13,
        name: 'Salmonellosis (Pullorum & Fowl Typhoid)',
        name_fr: 'Salmonellose (Pullorose & Typhose aviaire)',
        aliases: ['Salmonella pullorum', 'S. gallinarum'],
        aliases_fr: ['Salmonella pullorum', 'S. gallinarum'],
        scientificName: 'Salmonella enterica serovars',
        description: 'A systemic bacterial disease spread via eggs. Eradication programs reduce prevalence.',
        description_fr: "Une maladie bactérienne systémique transmise par les œufs. Les programmes d'éradication en réduisent la prévalence.",
        etiology: 'Bacterial',
        urgency: 'HIGH',
        zoonoticRisk: 'HIGH',
        isNotifiableInMorocco: true,
        speciesAffected: ['Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets', 'Dindes'],
        transmission: 'Vertical (eggs), contaminated environment',
        transmission_fr: 'Verticale (œufs), environnement contaminé',
        symptoms: ['Weakness, white diarrhea', 'High chick mortality', 'Reduced egg production'],
        symptoms_fr: ['Faiblesse, diarrhée blanche', 'Mortalité élevée des poussins', 'Baisse de ponte'],
        lesionsAtNecropsy: ['Enlarged liver', 'Enlarged spleen', 'Caseous material in ceca'],
        lesionsAtNecropsy_fr: ['Foie hypertrophié', 'Rate hypertrophiée', 'Matière caséeuse dans les caeca'],
        bodySystemAffected: ['Systemic', 'Digestive'],
        bodySystemAffected_fr: ['Systémique', 'Digestif'],
        treatment: 'Antibiotics (limited); cull infected flocks',
        treatment_fr: 'Antibiotiques (limités) ; abattre les troupeaux infectés',
        prevention: 'Test and eliminate breeders, biosecurity',
        prevention_fr: 'Tester et éliminer les reproducteurs, biosécurité',
        differentialDiagnosis: ['Coccidiosis', 'IB', 'mycoplasma'],
        differentialDiagnosis_fr: ['Coccidiose', 'BI', 'mycoplasme'],
        region: 'Morocco, Global',
        moroccoNote: 'Still present in unregulated backyard flocks.',
        moroccoNote_fr: 'Toujours présente dans les basses-cours non réglementées.',
        references: [{ text: 'WOAH Salmonellosis', url: 'https://www.woah.org/en/disease/salmonellosis/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 14,
        name: 'Aspergillosis',
        name_fr: 'Aspergillose',
        aliases: ['Brooder Pneumonia'],
        aliases_fr: ['Pneumonie de couveuse'],
        scientificName: 'Aspergillus fumigatus',
        description: 'A fungal pneumonia from moldy environments. Often fatal in chicks.',
        description_fr: "Une pneumonie fongique due à des environnements moisis. Souvent mortelle chez les poussins.",
        etiology: 'Fungal',
        urgency: 'HIGH',
        speciesAffected: ['All poultry'],
        speciesAffected_fr: ['Toutes les volailles'],
        transmission: 'Inhalation of spores from moldy feed/litter',
        transmission_fr: "Inhalation de spores provenant d'aliments/litière moisis",
        symptoms: ['Respiratory distress', 'Gasping', 'Weakness', 'High mortality'],
        symptoms_fr: ['Détresse respiratoire', 'Halètement', 'Faiblesse', 'Mortalité élevée'],
        lesionsAtNecropsy: ['Yellow nodules in lungs', 'Yellow nodules in air sacs', 'Fungal plaques'],
        lesionsAtNecropsy_fr: ['Nodules jaunes dans les poumons', 'Nodules jaunes dans les sacs aériens', 'Plaques fongiques'],
        bodySystemAffected: ['Respiratory'],
        bodySystemAffected_fr: ['Respiratoire'],
        treatment: 'Antifungals (amphotericin B, itraconazole) – limited success',
        treatment_fr: 'Antifongiques (amphotéricine B, itraconazole) – succès limité',
        prevention: 'Dry, clean litter; avoid moldy feed; good ventilation',
        prevention_fr: 'Litière sèche et propre ; éviter les aliments moisis ; bonne ventilation',
        differentialDiagnosis: ['CRD', 'IB', 'airsacculitis'],
        differentialDiagnosis_fr: ['MRC', 'BI', 'aérosacculite'],
        region: 'Morocco, Global',
        moroccoNote: 'Risk in humid seasons or poorly ventilated brooders.',
        moroccoNote_fr: 'Risque pendant les saisons humides ou dans les couveuses mal ventilées.',
        references: [{ text: 'Mycopathologia, 2020', url: 'https://scholar.google.com/scholar?q=Mycopathologia+Aspergillosis+poultry+2020' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 15,
        name: 'Infectious Coryza',
        name_fr: 'Coryza Infectieux',
        aliases: ['Avibacterium paragallinarum'],
        aliases_fr: ['Avibacterium paragallinarum'],
        scientificName: 'Avibacterium paragallinarum',
        description: 'A bacterial upper respiratory disease causing facial swelling. Spreads rapidly in dense flocks.',
        description_fr: "Une maladie respiratoire supérieure bactérienne provoquant un gonflement facial. Se propage rapidement dans les troupeaux denses.",
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        speciesAffected: ['Chickens', 'Pheasants'],
        speciesAffected_fr: ['Poulets', 'Faisans'],
        transmission: 'Direct contact, airborne',
        transmission_fr: 'Contact direct, aéroportée',
        symptoms: ['Swollen face', 'Nasal discharge', 'Sneezing', 'Reduced feed intake'],
        symptoms_fr: ['Face enflée', 'Écoulement nasal', 'Éternuements', "Baisse de consommation d'aliment"],
        lesionsAtNecropsy: ['Sinusitis with exudate', 'Tracheitis'],
        lesionsAtNecropsy_fr: ['Sinusite avec exsudat', 'Trachéite'],
        bodySystemAffected: ['Respiratory'],
        bodySystemAffected_fr: ['Respiratoire'],
        treatment: 'Sulfonamides, erythromycin',
        treatment_fr: 'Sulfamides, érythromycine',
        prevention: 'Vaccination, biosecurity, quarantine',
        prevention_fr: 'Vaccination, biosécurité, quarantaine',
        differentialDiagnosis: ['Mycoplasmosis', 'ILT', 'fowl cholera'],
        differentialDiagnosis_fr: ['Mycoplasmose', 'LTI', 'choléra aviaire'],
        region: 'Morocco, Global',
        moroccoNote: 'Common in multi-age backyard flocks.',
        moroccoNote_fr: 'Fréquent dans les basses-cours à âges multiples.',
        references: [{ text: 'FAO Coryza Manual', url: 'https://www.fao.org/poultry-production-and-products/en/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 16,
        name: 'Avian Tuberculosis (Mycobacteriosis)',
        name_fr: 'Tuberculose Aviaire (Mycobactériose)',
        aliases: ['Mycobacterium avium complex (MAC)'],
        aliases_fr: ['Complexe Mycobacterium avium (CMA)'],
        scientificName: 'Mycobacterium avium subsp. avium',
        description: 'A chronic, granulomatous bacterial disease caused by M. avium. Not treatable; control relies on culling and hygiene.',
        description_fr: 'Une maladie bactérienne chronique et granulomateuse causée par M. avium. Non traitable ; le contrôle repose sur l’abattage et l’hygiène.',
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        zoonoticRisk: 'MODERATE',
        speciesAffected: ['Chickens', 'Turkeys', 'Waterfowl'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Oiseaux d’eau'],
        transmission: 'Ingestion of contaminated soil/litter, inhalation, fomites',
        transmission_fr: 'Ingestion de sol/litière contaminés, inhalation, fomites',
        symptoms: ['Progressive weight loss', 'Lethargy, pale combs', 'Lameness'],
        symptoms_fr: ['Perte de poids progressive', 'Léthargie, crêtes pâles', 'Boiterie'],
        lesionsAtNecropsy: ['Caseous nodules in liver', 'Caseous nodules in spleen', 'Caseous nodules in lungs', 'Granulomatous inflammation', 'Bone lesions'],
        lesionsAtNecropsy_fr: ['Nodules caséeux dans le foie', 'Nodules caséeux dans la rate', 'Nodules caséeux dans les poumons', 'Inflammation granulomateuse', 'Lésions osseuses'],
        bodySystemAffected: ['Systemic', 'Immune'],
        bodySystemAffected_fr: ['Systémique', 'Immunitaire'],
        treatment: 'None – zoonotic risk; cull affected birds',
        treatment_fr: 'Aucun – risque zoonotique ; abattre les oiseaux affectés',
        prevention: 'Remove infected birds, clean environment, avoid wild bird access',
        prevention_fr: 'Retirer les oiseaux infectés, nettoyer l’environnement, éviter l’accès des oiseaux sauvages',
        differentialDiagnosis: ['Lymphoid leukosis', 'Marek’s disease', 'salmonellosis'],
        differentialDiagnosis_fr: ['Leucose lymphoïde', 'Maladie de Marek', 'salmonellose'],
        region: 'Morocco, Global',
        moroccoNote: 'Rare but possible in long-lived backyard flocks or free-range systems with soil exposure.',
        moroccoNote_fr: 'Rare mais possible dans les basses-cours à longue durée de vie ou les systèmes en plein air avec exposition au sol.',
        references: [
            { text: 'WOAH Avian Tuberculosis', url: 'https://www.woah.org/en/disease/avian-tuberculosis/' },
            { text: 'Avian Pathology, 2017', url: 'https://scholar.google.com/scholar?q=Avian+Pathology+Avian+Tuberculosis+2017' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 17,
        name: 'Infectious Synovitis (Mycoplasma synoviae)',
        name_fr: 'Synovite Infectieuse (Mycoplasma synoviae)',
        aliases: ['MS infection'],
        aliases_fr: ['Infection à MS'],
        scientificName: 'Mycoplasma synoviae',
        description: 'A mycoplasma causing joint inflammation and respiratory signs. Spreads via eggs and air.',
        description_fr: 'Un mycoplasme provoquant une inflammation articulaire et des signes respiratoires. Se propage par les œufs et l’air.',
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        speciesAffected: ['Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets', 'Dindes'],
        transmission: 'Vertical (eggs), aerosol, contaminated equipment',
        transmission_fr: 'Verticale (œufs), aérosol, équipement contaminé',
        symptoms: ['Lameness', 'Swollen joints', 'Breast blisters', 'Reduced growth', 'Reduced egg production', 'Reluctance to walk'],
        symptoms_fr: ['Boiterie', 'Articulations enflées', 'Vésicules sur le bréchet', 'Croissance réduite', 'Baisse de ponte', 'Réticence à marcher'],
        lesionsAtNecropsy: ['Cloudy synovial fluid in joints', 'Caseous exudate in tendons', 'Thickened air sacs', 'Cloudy air sacs'],
        lesionsAtNecropsy_fr: ['Liquide synovial trouble dans les articulations', 'Exsudat caséeux dans les tendons', 'Sacs aériens épaissis', 'Sacs aériens opaques'],
        bodySystemAffected: ['Musculoskeletal', 'Respiratory'],
        bodySystemAffected_fr: ['Musculosquelettique', 'Respiratoire'],
        treatment: 'Tylosin, lincomycin, tiamulin (veterinary prescription)',
        treatment_fr: 'Tylosine, lincomycine, tiamuline (prescription vétérinaire)',
        prevention: 'Clean hatcheries, biosecurity, vaccination (Vaxsafe MS)',
        prevention_fr: 'Propreté des couvoirs, biosécurité, vaccination (Vaxsafe MS)',
        differentialDiagnosis: ['Viral tenosynovitis', 'BCO', 'arthritis from E. coli'],
        differentialDiagnosis_fr: ['Ténosynovite virale', 'BCO', 'arthrite à E. coli'],
        region: 'Morocco, Global',
        moroccoNote: 'Often underdiagnosed; can mimic other joint diseases in broilers.',
        moroccoNote_fr: 'Souvent sous-diagnostiquée ; peut imiter d’autres maladies articulaires chez les poulets de chair.',
        references: [
            { text: 'USDA MS Guidelines', url: 'https://www.aphis.usda.gov/animal_health/animal_diseases/npep/downloads/ms-pamphlet.pdf' },
            { text: 'Poultry Science, 2020', url: 'https://scholar.google.com/scholar?q=Poultry+Science+Mycoplasma+synoviae+2020' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 18,
        name: 'Blackhead Disease (Histomoniasis)',
        name_fr: 'Histomonose (Maladie de la tête noire)',
        aliases: ['Histomoniasis', 'Turkey Blackhead'],
        aliases_fr: ['Histomonose', 'Tête noire de la dinde'],
        scientificName: 'Histomonas meleagridis',
        description: 'A protozoal disease fatal to turkeys. Chickens act as reservoirs via cecal worms.',
        description_fr: 'Une maladie protozoaire mortelle pour les dindes. Les poulets agissent comme réservoirs via les vers cæcaux.',
        etiology: 'Parasitic',
        urgency: 'HIGH',
        speciesAffected: ['Turkeys', 'Chickens', 'Game Birds'],
        speciesAffected_fr: ['Dindes', 'Poulets', 'Gibier à plumes'],
        transmission: 'Via Heterakis gallinarum (cecal worm) eggs or earthworms',
        transmission_fr: 'Via les œufs de Heterakis gallinarum (ver cæcal) ou les vers de terre',
        symptoms: ['Sulphur-yellow diarrhea', 'Drooping wings, lethargy', 'Cyanotic head (darkening)', 'High mortality'],
        symptoms_fr: ['Diarrhée jaune soufre', 'Ailes pendantes, léthargie', 'Tête cyanosée (noircissement)', 'Mortalité élevée'],
        lesionsAtNecropsy: ['Caseous cecal cores', 'Circular necrotic lesions on liver'],
        lesionsAtNecropsy_fr: ['Cylindres caséeux dans les caeca', 'Lésions nécrotiques circulaires sur le foie'],
        bodySystemAffected: ['Digestive', 'Systemic'],
        bodySystemAffected_fr: ['Digestif', 'Systémique'],
        treatment: 'None approved; historical use of nitarsone (now banned in many regions)',
        treatment_fr: 'Aucun approuvé ; utilisation historique du nitarsone (maintenant interdit dans de nombreuses régions)',
        prevention: 'Deworm for Heterakis, avoid mixed turkey-chicken flocks, clean litter',
        prevention_fr: 'Vermifuger contre Heterakis, éviter les élevages mixtes dinde-poulet, litière propre',
        differentialDiagnosis: ['Coccidiosis', 'salmonellosis', 'avian cholera'],
        differentialDiagnosis_fr: ['Coccidiose', 'salmonellose', 'choléra aviaire'],
        region: 'Morocco, Global',
        moroccoNote: 'Risk in free-range or organic systems with soil exposure and earthworms.',
        moroccoNote_fr: 'Risque dans les systèmes en plein air ou biologiques avec exposition au sol et aux vers de terre.',
        references: [
            { text: 'FAO Blackhead Control', url: 'https://www.fao.org/poultry-production-and-products/en/' },
            { text: 'Veterinary Parasitology, 2022', url: 'https://scholar.google.com/scholar?q=Veterinary+Parasitology+Histomoniasis+2022' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 19,
        name: 'Viral Tenosynovitis (Avian Reovirus)',
        name_fr: 'Ténosynovite Virale (Réovirus Aviaire)',
        aliases: ['Viral Arthritis', 'Tenosynovitis'],
        aliases_fr: ['Arthrite Virale', 'Ténosynovite'],
        scientificName: 'Orthoreovirus (Avian reovirus)',
        description: 'A viral infection causing swelling and rupture of tendons in young broilers. Preventable with vaccination.',
        description_fr: 'Une infection virale provoquant le gonflement et la rupture des tendons chez les jeunes poulets de chair. Prévention possible par la vaccination.',
        etiology: 'Viral',
        urgency: 'MEDIUM',
        speciesAffected: ['Broilers', 'Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets de chair', 'Poulets', 'Dindes'],
        transmission: 'Vertical (eggs), fecal-oral, contaminated environment',
        transmission_fr: 'Verticale (œufs), féco-orale, environnement contaminé',
        symptoms: ['Swollen hock joints', 'Lameness', 'Reluctance to move', 'Tendon rupture', 'Poor growth'],
        symptoms_fr: ['Jarrets enflés', 'Boiterie', 'Réticence à se déplacer', 'Rupture de tendon', 'Mauvaise croissance'],
        lesionsAtNecropsy: ['Fluid-filled tendon sheaths', 'Tendon necrosis', 'Ruptured gastrocnemius tendon'],
        lesionsAtNecropsy_fr: ['Gaines tendineuses remplies de liquide', 'Nécrose du tendon', 'Rupture du tendon gastrocnémien'],
        bodySystemAffected: ['Musculoskeletal'],
        bodySystemAffected_fr: ['Musculosquelettique'],
        treatment: 'None specific; antibiotics for secondary infections',
        treatment_fr: 'Aucun traitement spécifique ; antibiotiques pour les infections secondaires',
        prevention: 'Breeder vaccination, biosecurity, all-in/all-out management',
        prevention_fr: 'Vaccination des reproducteurs, biosécurité, gestion en bande unique',
        differentialDiagnosis: ['Bacterial chondronecrosis (BCO)', 'Staphylococcus arthritis', 'MS'],
        differentialDiagnosis_fr: ['Chondronécrose bactérienne (BCO)', 'Arthrite à Staphylocoque', 'MS'],
        region: 'Morocco, Global',
        moroccoNote: 'Increasing in fast-growing broiler farms with high stocking density.',
        moroccoNote_fr: 'En augmentation dans les élevages de poulets de chair à croissance rapide avec une forte densité.',
        references: [{ text: 'Avian Diseases, 2019', url: 'https://scholar.google.com/scholar?q=Avian+Diseases+Avian+Reovirus+2019' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 20,
        name: 'Lymphoid Leukosis',
        name_fr: 'Leucose Lymphoïde',
        aliases: ['ALV (Avian Leukosis Virus)'],
        aliases_fr: ['VLA (Virus de la Leucose Aviaire)'],
        scientificName: 'Gallid alpharetrovirus (Avian leukosis virus)',
        description: 'A retrovirus causing B-cell tumors, primarily in older chickens. Controlled by eradication.',
        description_fr: 'Un rétrovirus provoquant des tumeurs des lymphocytes B, principalement chez les poulets plus âgés. Contrôlé par éradication.',
        etiology: 'Viral',
        urgency: 'HIGH',
        speciesAffected: ['Chickens'],
        speciesAffected_fr: ['Poulets'],
        transmission: 'Vertical (eggs), contaminated equipment',
        transmission_fr: 'Verticale (œufs), équipement contaminé',
        symptoms: ['Slow decline, weight loss', 'Enlarged abdomen', 'Pale combs', 'Sudden death'],
        symptoms_fr: ['Déclin lent, perte de poids', 'Abdomen hypertrophié', 'Crêtes pâles', 'Mort subite'],
        lesionsAtNecropsy: ['Tumors in liver', 'Tumors in bursa', 'Tumors in spleen'],
        lesionsAtNecropsy_fr: ['Tumeurs au foie', 'Tumeurs à la bourse de Fabricius', 'Tumeurs à la rate'],
        bodySystemAffected: ['Immune', 'Systemic'],
        bodySystemAffected_fr: ['Immunitaire', 'Systémique'],
        treatment: 'None',
        treatment_fr: 'Aucun',
        prevention: 'Eradication programs, use of ALV-free breeder flocks',
        prevention_fr: 'Programmes d’éradication, utilisation de troupeaux de reproducteurs exempts de VLA',
        differentialDiagnosis: ['Marek’s disease', 'myelocytomatosis', 'fatty liver'],
        differentialDiagnosis_fr: ['Maladie de Marek', 'myélocytomatose', 'stéatose hépatique'],
        region: 'Morocco, Global',
        moroccoNote: 'Less common than Marek’s, but still present in some commercial lines.',
        moroccoNote_fr: 'Moins fréquente que la maladie de Marek, mais toujours présente dans certaines lignées commerciales.',
        references: [{ text: 'WOAH Lymphoid Leukosis', url: 'https://www.woah.org/en/disease/avian-leukosis-viruses/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 21,
        name: 'Bacterial Chondronecrosis with Osteomyelitis (BCO)',
        name_fr: 'Chondronécrose Bactérienne avec Ostéomyélite (BCO)',
        aliases: ['"Broken Down" syndrome'],
        aliases_fr: ['Syndrome des "pattes cassées"'],
        scientificName: 'Hematogenous bacterial infection (e.g., E. coli, Staphylococcus aureus)',
        description: 'A metabolic-bacterial condition causing lameness and leg weakness in fast-growing birds.',
        description_fr: 'Une affection métabolico-bactérienne provoquant boiterie et faiblesse des pattes chez les oiseaux à croissance rapide.',
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        speciesAffected: ['Broilers', 'Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets de chair', 'Poulets', 'Dindes'],
        transmission: 'Bacteria enter bloodstream from gut or footpad lesions',
        transmission_fr: 'Les bactéries pénètrent dans la circulation sanguine à partir de lésions intestinales ou des coussinets plantaires',
        symptoms: ['Lameness', 'Reluctance to walk', 'Leg fractures', 'High culling rate'],
        symptoms_fr: ['Boiterie', 'Réticence à marcher', 'Fractures des pattes', 'Taux de réforme élevé'],
        lesionsAtNecropsy: ['Necrotic femoral head', 'Bacterial colonies in bone', 'Inflamed growth plates'],
        lesionsAtNecropsy_fr: ['Nécrose de la tête fémorale', 'Colonies bactériennes dans l’os', 'Plaques de croissance enflammées'],
        bodySystemAffected: ['Musculoskeletal'],
        bodySystemAffected_fr: ['Musculosquelettique'],
        treatment: 'Limited; remove affected birds',
        treatment_fr: 'Limité ; retirer les oiseaux affectés',
        prevention: 'Reduce growth rate stress, improve litter, footpad health, balanced nutrition',
        prevention_fr: 'Réduire le stress lié à la croissance rapide, améliorer la litière, la santé des coussinets plantaires, nutrition équilibrée',
        differentialDiagnosis: ['Viral tenosynovitis', 'tibial dyschondroplasia', 'trauma'],
        differentialDiagnosis_fr: ['Ténosynovite virale', 'dyschondroplasie tibiale', 'traumatisme'],
        region: 'Morocco, Global',
        moroccoNote: 'Increasing with intensive broiler production and poor litter management.',
        moroccoNote_fr: 'En augmentation avec la production intensive de poulets de chair et une mauvaise gestion de la litière.',
        references: [{ text: 'Poultry Science, 2021', url: 'https://scholar.google.com/scholar?q=Poultry+Science+Bacterial+Chondronecrosis+Osteomyelitis+2021' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 22,
        name: 'Fatty Liver Hemorrhagic Syndrome (FLHS)',
        name_fr: 'Syndrome Hémorragique du Foie Gras (FLHS)',
        aliases: ['Fatty Liver Syndrome'],
        aliases_fr: ['Syndrome du foie gras'],
        scientificName: 'Metabolic disorder (not infectious)',
        description: 'A metabolic disorder in laying hens due to energy imbalance. Liver rupture causes sudden death.',
        description_fr: 'Un trouble métabolique chez les poules pondeuses dû à un déséquilibre énergétique. La rupture du foie provoque une mort subite.',
        etiology: 'Other',
        urgency: 'MEDIUM',
        speciesAffected: ['Layers', 'Chickens'],
        speciesAffected_fr: ['Pondeuses', 'Poulets'],
        transmission: 'Dietary imbalance, lack of exercise',
        transmission_fr: 'Déséquilibre alimentaire, manque d’exercice',
        symptoms: ['Sudden death (often at night)', 'Obesity, pale comb', 'Enlarged abdomen', 'Reduced egg production'],
        symptoms_fr: ['Mort subite (souvent la nuit)', 'Obésité, crête pâle', 'Abdomen hypertrophié', 'Baisse de ponte'],
        lesionsAtNecropsy: ['Enlarged liver', 'Friable liver', 'Yellow liver', 'Blood clots in abdominal cavity'],
        lesionsAtNecropsy_fr: ['Foie hypertrophié', 'Foie friable', 'Foie jaune', 'Caillots de sang dans la cavité abdominale'],
        bodySystemAffected: ['Metabolic', 'Reproductive'],
        bodySystemAffected_fr: ['Métabolique', 'Reproducteur'],
        treatment: 'None after onset; remove dead birds',
        treatment_fr: 'Aucun après apparition ; retirer les oiseaux morts',
        prevention: 'Balanced diet (limit energy), methionine/choline, foraging, reduce stress',
        prevention_fr: 'Régime équilibré (limiter l’énergie), méthionine/choline, accès au parcours, réduire le stress',
        differentialDiagnosis: ['Egg yolk peritonitis', 'internal laying', 'avian influenza'],
        differentialDiagnosis_fr: ['Péritonite vitelline', 'ponte interne', 'grippe aviaire'],
        region: 'Morocco, Global',
        moroccoNote: 'Seen in cage layers with high-energy diets and low activity.',
        moroccoNote_fr: 'Observé chez les pondeuses en cage avec des régimes à haute énergie et une faible activité.',
        references: [
            { text: 'FAO Metabolic Disorders', url: 'https://www.fao.org/poultry-production-and-products/en/' },
            { text: 'Avian Physiology, 5th ed.', url: 'https://scholar.google.com/scholar?q=Avian+Physiology+Fatty+Liver+Hemorrhagic+Syndrome' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 23,
        name: 'Tibial Dyschondroplasia (TD)',
        name_fr: 'Dyschondroplasie Tibiale (DT)',
        aliases: ['Cartilage plug disease'],
        aliases_fr: ['Maladie du bouchon cartilagineux'],
        scientificName: 'Metabolic disorder (defective endochondral ossification)',
        description: 'A developmental disorder where cartilage fails to turn into bone, causing lameness.',
        description_fr: 'Un trouble du développement où le cartilage ne se transforme pas en os, provoquant une boiterie.',
        etiology: 'Other',
        urgency: 'MEDIUM',
        speciesAffected: ['Broilers', 'Chickens'],
        speciesAffected_fr: ['Poulets de chair', 'Poulets'],
        transmission: 'Dietary imbalance (Ca/P/Vit D), genetics',
        transmission_fr: 'Déséquilibre alimentaire (Ca/P/Vit D), génétique',
        symptoms: ['Lameness', 'Shortened legs', 'Reluctance to stand', 'Hock swelling'],
        symptoms_fr: ['Boiterie', 'Pattes raccourcies', 'Réticence à se tenir debout', 'Gonflement du jarret'],
        lesionsAtNecropsy: ['Non-vascularized cartilage plug in growth plate', 'Soft tibial growth plate', 'Widened tibial growth plate'],
        lesionsAtNecropsy_fr: ['Bouchon de cartilage non vascularisé dans la plaque de croissance', 'Plaque de croissance tibiale molle', 'Plaque de croissance tibiale élargie'],
        bodySystemAffected: ['Musculoskeletal'],
        bodySystemAffected_fr: ['Musculosquelettique'],
        treatment: 'None',
        treatment_fr: 'Aucun',
        prevention: 'Balanced Ca/P/Vit D, avoid excessive protein early, use resistant strains',
        prevention_fr: 'Équilibre en Ca/P/Vit D, éviter un excès de protéines au début, utiliser des souches résistantes',
        differentialDiagnosis: ['BCO', 'viral tenosynovitis', 'rickets'],
        differentialDiagnosis_fr: ['BCO', 'ténosynovite virale', 'rachitisme'],
        region: 'Morocco, Global',
        moroccoNote: 'A welfare and economic issue in rapidly growing broiler farms.',
        moroccoNote_fr: 'Un problème de bien-être et économique dans les élevages de poulets de chair à croissance rapide.',
        references: [{ text: 'Poultry Science, 2018', url: 'https://scholar.google.com/scholar?q=Poultry+Science+Tibial+Dyschondroplasia+2018' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 24,
        name: 'External Parasites (Mites & Lice)',
        name_fr: 'Parasites Externes (Acariens & Poux)',
        aliases: ['Red mite (Dermanyssus gallinae)', 'Northern fowl mite', 'chicken lice'],
        aliases_fr: ['Pou rouge (Dermanyssus gallinae)', 'Pou du Nord', 'poux du poulet'],
        scientificName: 'Dermanyssus gallinae, Ornithonyssus sylvarium, Menacanthus stramineus',
        description: 'Mites and lice cause irritation, anemia, and production loss. Control requires environmental treatment.',
        description_fr: 'Les acariens et les poux provoquent irritation, anémie et perte de production. Le contrôle nécessite un traitement de l’environnement.',
        etiology: 'Parasitic',
        urgency: 'LOW',
        speciesAffected: ['All poultry'],
        speciesAffected_fr: ['Toutes les volailles'],
        transmission: 'Direct contact, contaminated coops, wild birds',
        transmission_fr: 'Contact direct, poulaillers contaminés, oiseaux sauvages',
        symptoms: ['Restlessness, feather loss', 'Anemia, pale combs', 'Reduced egg production', 'Blood spots on eggs (red mites)'],
        symptoms_fr: ['Agitation, perte de plumes', 'Anémie, crêtes pâles', 'Baisse de ponte', 'Taches de sang sur les œufs (poux rouges)'],
        lesionsAtNecropsy: ['Skin irritation', 'Scabs', 'Anemia'],
        lesionsAtNecropsy_fr: ['Irritation cutanée', 'Croûtes', 'Anémie'],
        bodySystemAffected: ['Integumentary', 'Systemic'],
        bodySystemAffected_fr: ['Tégumentaire', 'Systémique'],
        treatment: 'Permethrin, ivermectin (off-label), diatomaceous earth (limited)',
        treatment_fr: 'Perméthrine, ivermectine (hors AMM), terre de diatomées (limité)',
        prevention: 'Regular coop cleaning, disinfection, dust baths, biocontrol (predator mites)',
        prevention_fr: 'Nettoyage régulier du poulailler, désinfection, bains de poussière, lutte biologique (acariens prédateurs)',
        differentialDiagnosis: ['Molting', 'nutritional deficiency', 'internal parasites'],
        differentialDiagnosis_fr: ['Mue', 'carence nutritionnelle', 'parasites internes'],
        region: 'Morocco, Global',
        moroccoNote: 'Common in older or poorly maintained backyard coops.',
        moroccoNote_fr: 'Fréquent dans les basses-cours anciennes ou mal entretenues.',
        references: [
            { text: 'FAO Ectoparasite Guide', url: 'https://www.fao.org/poultry-production-and-products/en/' },
            { text: 'Veterinary Parasitology, 2020', url: 'https://scholar.google.com/scholar?q=Veterinary+Parasitology+poultry+mites+lice+2020' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 25,
        name: 'Internal Parasites (Roundworms, Tapeworms)',
        name_fr: 'Parasites Internes (Ascaris, Ténias)',
        aliases: ['Ascaridia galli', 'Heterakis gallinarum', 'Raillietina spp.'],
        aliases_fr: ['Ascaridia galli', 'Heterakis gallinarum', 'Raillietina spp.'],
        scientificName: 'Ascaridia galli, Heterakis gallinarum, Raillietina spp.',
        description: 'Intestinal worms cause malnutrition and reduced performance. Preventable with rotation and deworming.',
        description_fr: 'Les vers intestinaux provoquent malnutrition et baisse de performance. Prévention par rotation des parcours et vermifugation.',
        etiology: 'Parasitic',
        urgency: 'MEDIUM',
        speciesAffected: ['Chickens', 'Turkeys', 'Game Birds'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Gibier à plumes'],
        transmission: 'Ingestion of eggs from soil, earthworms (for Heterakis)',
        transmission_fr: 'Ingestion d’œufs du sol, vers de terre (pour Heterakis)',
        symptoms: ['Weight loss, poor growth', 'Diarrhea', 'Intestinal blockage', 'Reduced egg production'],
        symptoms_fr: ['Perte de poids, mauvaise croissance', 'Diarrhée', 'Occlusion intestinale', 'Baisse de ponte'],
        lesionsAtNecropsy: ['Adult worms in intestines', 'Thickened gut wall', 'Cecal cores'],
        lesionsAtNecropsy_fr: ['Vers adultes dans les intestins', 'Paroi intestinale épaissie', 'Cylindres cæcaux'],
        bodySystemAffected: ['Digestive'],
        bodySystemAffected_fr: ['Digestif'],
        treatment: 'Fenbendazole, levamisole, flubendazole',
        treatment_fr: 'Fenbendazole, lévamisole, flubendazole',
        prevention: 'Rotate pastures, clean litter, deworming program',
        prevention_fr: 'Rotation des pâturages, litière propre, programme de vermifugation',
        differentialDiagnosis: ['Coccidiosis', 'salmonellosis', 'nutritional deficiency'],
        differentialDiagnosis_fr: ['Coccidiose', 'salmonellose', 'carence nutritionnelle'],
        region: 'Morocco, Global',
        moroccoNote: 'High prevalence in free-range and backyard flocks.',
        moroccoNote_fr: 'Prévalence élevée dans les élevages en plein air et les basses-cours.',
        references: [
            { text: 'WOAH Helminth Control', url: 'https://www.woah.org/' },
            { text: 'FAO Manual on Poultry Parasites', url: 'https://www.fao.org/documents/card/en/c/b0a03e67-54b9-5365-a63e-a10b91129f12/' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 26,
        name: 'Vent Gleet (Cloacal Candidiasis)',
        name_fr: 'Cloacite (Candidose cloacale)',
        aliases: ['"Cock\'s Comb Fungus"'],
        aliases_fr: [''],
        scientificName: 'Candida albicans',
        description: 'A fungal infection of the cloaca, often linked to antibiotic use or stress.',
        description_fr: 'Une infection fongique du cloaque, souvent liée à l’utilisation d’antibiotiques ou au stress.',
        etiology: 'Fungal',
        urgency: 'LOW',
        speciesAffected: ['Chickens', 'Layers'],
        speciesAffected_fr: ['Poulets', 'Pondeuses'],
        transmission: 'Overgrowth due to antibiotics, stress, poor hygiene',
        transmission_fr: 'Prolifération due aux antibiotiques, au stress, à une mauvaise hygiène',
        symptoms: ['Swollen, inflamed vent', 'White fungal plaques', 'Egg binding'],
        symptoms_fr: ['Cloaque enflé et enflammé', 'Plaques fongiques blanches', 'Rétention d’œuf'],
        lesionsAtNecropsy: ['White plaques in cloaca', 'Inflammation of cloaca', 'Edema of cloaca'],
        lesionsAtNecropsy_fr: ['Plaques blanches dans le cloaque', 'Inflammation du cloaque', 'Œdème du cloaque'],
        bodySystemAffected: ['Reproductive', 'Integumentary'],
        bodySystemAffected_fr: ['Reproducteur', 'Tégumentaire'],
        treatment: 'Nystatin (oral/topical), improve hygiene',
        treatment_fr: 'Nystatine (orale/topique), améliorer l’hygiène',
        prevention: 'Avoid unnecessary antibiotics, clean nesting boxes, balanced diet',
        prevention_fr: 'Éviter les antibiotiques inutiles, nettoyer les pondoirs, alimentation équilibrée',
        differentialDiagnosis: ['Prolapsed cloaca', 'bacterial infection', 'tumor'],
        differentialDiagnosis_fr: ['Prolapsus du cloaque', 'infection bactérienne', 'tumeur'],
        region: 'Morocco, Global',
        moroccoNote: 'Underreported; often mistaken for prolapse or infection.',
        moroccoNote_fr: 'Sous-déclarée ; souvent confondue avec un prolapsus ou une infection.',
        references: [{ text: 'Avian Medicine: Principles and Application, 2020', url: 'https://scholar.google.com/scholar?q=Avian+Medicine+Principles+and+Application+Vent+Gleet' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 27,
        name: 'Avian Spirochetosis',
        name_fr: 'Spirochétose Aviaire',
        aliases: ['Fowl Spirochetosis'],
        aliases_fr: ['Spirochétose de la volaille'],
        scientificName: 'Borrelia anserina',
        description: 'A tick-borne bacterial disease with high mortality. Control depends on vector management.',
        description_fr: 'Une maladie bactérienne transmise par les tiques, à mortalité élevée. Le contrôle dépend de la gestion du vecteur.',
        etiology: 'Bacterial',
        urgency: 'HIGH',
        speciesAffected: ['Chickens', 'Turkeys', 'Waterfowl'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Oiseaux d’eau'],
        transmission: 'Via soft ticks (Argas spp.), contaminated eggs',
        transmission_fr: 'Via les tiques molles (Argas spp.), œufs contaminés',
        symptoms: ['Sudden fever', 'Green diarrhea', 'Paralysis', 'High mortality'],
        symptoms_fr: ['Fièvre soudaine', 'Diarrhée verdâtre', 'Paralysie', 'Mortalité élevée'],
        lesionsAtNecropsy: ['Enlarged liver', 'Enlarged spleen', 'Hemorrhages in organs'],
        lesionsAtNecropsy_fr: ['Foie hypertrophié', 'Rate hypertrophiée', 'Hémorragies sur les organes'],
        bodySystemAffected: ['Systemic', 'Nervous'],
        bodySystemAffected_fr: ['Systémique', 'Nerveux'],
        treatment: 'Penicillin, tetracyclines (early)',
        treatment_fr: 'Pénicilline, tétracyclines (en début de maladie)',
        prevention: 'Tick control, avoid tick-infested areas',
        prevention_fr: 'Contrôle des tiques, éviter les zones infestées de tiques',
        differentialDiagnosis: ['Fowl cholera', 'avian influenza', 'Marek’s'],
        differentialDiagnosis_fr: ['Choléra aviaire', 'grippe aviaire', 'Marek'],
        region: 'Morocco, Global',
        moroccoNote: 'Possible in rural areas with tick presence, especially near wetlands.',
        moroccoNote_fr: 'Possible dans les zones rurales avec présence de tiques, en particulier près des zones humides.',
        references: [{ text: 'FAO Tick-Borne Diseases', url: 'https://www.fao.org/documents/card/en/c/d9e84777-62f3-529a-81f1-4325a74a1595/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 28,
        name: 'Perosis (Slipped Tendon)',
        name_fr: 'Pérosis (Tendon déplacé)',
        aliases: ['Tibia-tarsal joint displacement'],
        aliases_fr: ['Déplacement de l’articulation tibio-tarsienne'],
        scientificName: 'Nutritional deficiency (biotin, choline, manganese)',
        description: 'A nutritional disorder causing leg deformities in young birds. Preventable with proper feed.',
        description_fr: 'Un trouble nutritionnel provoquant des déformations des pattes chez les jeunes oiseaux. Prévention par une alimentation adéquate.',
        etiology: 'Other',
        urgency: 'LOW',
        speciesAffected: ['Chickens', 'Turkeys'],
        speciesAffected_fr: ['Poulets', 'Dindes'],
        transmission: 'Deficient starter diet',
        transmission_fr: 'Aliment de démarrage carencé',
        symptoms: ['Swollen hock', 'Rotated tibia', 'Inability to stand', 'Lameness'],
        symptoms_fr: ['Jarret enflé', 'Tibia tourné', 'Incapacité à se tenir debout', 'Boiterie'],
        lesionsAtNecropsy: ['Displaced tibiotarsal joint', 'Enlarged growth plate'],
        lesionsAtNecropsy_fr: ['Articulation tibio-tarsienne déplacée', 'Plaque de croissance élargie'],
        bodySystemAffected: ['Musculoskeletal'],
        bodySystemAffected_fr: ['Musculosquelettique'],
        treatment: 'None once severe; correct diet for flock',
        treatment_fr: 'Aucun une fois sévère ; corriger l’alimentation du troupeau',
        prevention: 'Balanced starter feed with essential micronutrients',
        prevention_fr: 'Aliment de démarrage équilibré avec les micronutriments essentiels',
        differentialDiagnosis: ['Viral tenosynovitis', 'BCO', 'trauma'],
        differentialDiagnosis_fr: ['Ténosynovite virale', 'BCO', 'traumatisme'],
        region: 'Morocco, Global',
        moroccoNote: 'Seen in backyard flocks fed unbalanced kitchen scraps.',
        moroccoNote_fr: 'Observé dans les basses-cours nourries avec des restes de cuisine déséquilibrés.',
        references: [{ text: 'Poultry Nutrition Guide, FAO, 2011', url: 'https://www.fao.org/documents/card/en/c/28a8677c-a4d1-56c6-ac7c-2b998c397521/' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 29,
        name: 'Heat Stress',
        name_fr: 'Stress Thermique',
        aliases: ['Hyperthermia'],
        aliases_fr: ['Hyperthermie'],
        scientificName: 'Environmental condition (not infectious)',
        description: 'A life-threatening condition due to high heat/humidity. Requires immediate cooling and management.',
        description_fr: 'Une condition potentiellement mortelle due à une chaleur/humidité élevée. Nécessite un refroidissement et une gestion immédiats.',
        etiology: 'Other',
        urgency: 'HIGH',
        speciesAffected: ['All poultry', 'Broilers', 'Layers'],
        speciesAffected_fr: ['Toutes les volailles', 'Poulets de chair', 'Pondeuses'],
        transmission: 'High temperature/humidity',
        transmission_fr: 'Température/humidité élevée',
        symptoms: ['Panting, wing spreading', 'Reduced feed intake', 'Reduced egg production', 'Sudden death'],
        symptoms_fr: ['Halètement, ailes écartées', 'Baisse de consommation d’aliment', 'Baisse de ponte', 'Mort subite'],
        lesionsAtNecropsy: ['Congested organs'],
        lesionsAtNecropsy_fr: ['Organes congestionnés'],
        bodySystemAffected: ['Systemic', 'Metabolic'],
        bodySystemAffected_fr: ['Systémique', 'Métabolique'],
        treatment: 'Cool birds (mist, fans), provide cool water, electrolytes',
        treatment_fr: 'Refroidir les oiseaux (brumisation, ventilateurs), fournir de l’eau fraîche, des électrolytes',
        prevention: 'Shade, ventilation, misting, adjust feeding times',
        prevention_fr: 'Ombre, ventilation, brumisation, ajuster les heures d’alimentation',
        differentialDiagnosis: ['Respiratory diseases', 'heart failure', 'toxicosis'],
        differentialDiagnosis_fr: ['Maladies respiratoires', 'insuffisance cardiaque', 'toxicose'],
        region: 'Morocco, Global',
        moroccoNote: 'Major issue in summer months, especially in inland regions like Meknes or Marrakech.',
        moroccoNote_fr: 'Problème majeur pendant les mois d’été, en particulier dans les régions intérieures comme Meknès ou Marrakech.',
        references: [
            { text: 'FAO Heat Stress Management', url: 'https://www.fao.org/poultry-production-and-products/en/' },
            { text: 'Avian Physiology', url: 'https://scholar.google.com/scholar?q=Avian+Physiology+Heat+Stress' }
        ],
        lastReviewed: '2025-04-05',
    },
    {
        id: 30,
        name: 'Egg Binding',
        name_fr: 'Rétention d’Œuf',
        aliases: ['Dystocia'],
        aliases_fr: ['Dystocie'],
        scientificName: 'Mechanical/physiological obstruction',
        description: 'A life-threatening condition where an egg cannot pass. Requires prompt intervention.',
        description_fr: 'Une condition potentiellement mortelle où un œuf ne peut pas passer. Nécessite une intervention rapide.',
        etiology: 'Other',
        urgency: 'HIGH',
        speciesAffected: ['Layers', 'Chickens'],
        speciesAffected_fr: ['Pondeuses', 'Poulets'],
        transmission: 'Physiological — not infectious',
        transmission_fr: 'Physiologique — non infectieux',
        symptoms: ['Straining, lethargy', 'Fluffed feathers', 'Swollen vent'],
        symptoms_fr: ['Efforts, léthargie', 'Plumes ébouriffées', 'Cloaque enflé'],
        lesionsAtNecropsy: ['Egg stuck in oviduct', 'Egg stuck in cloaca', 'Hemorrhage'],
        lesionsAtNecropsy_fr: ['Œuf coincé dans l’oviducte', 'Œuf coincé dans le cloaque', 'Hémorragie'],
        bodySystemAffected: ['Reproductive'],
        bodySystemAffected_fr: ['Reproducteur'],
        treatment: 'Lubrication, warm bath, calcium; vet may break yolk or perform C-section',
        treatment_fr: 'Lubrification, bain chaud, calcium ; le vétérinaire peut casser le jaune ou pratiquer une césarienne',
        prevention: 'Balanced Ca/P, avoid obesity, provide nesting privacy',
        prevention_fr: 'Équilibre Ca/P, éviter l’obésité, fournir des pondoirs isolés',
        differentialDiagnosis: ['Salpingitis', 'internal laying', 'tumor'],
        differentialDiagnosis_fr: ['Salpingite', 'ponte interne', 'tumeur'],
        region: 'Morocco, Global',
        moroccoNote: 'Common in backyard hens fed improper diets or kept in stressful environments.',
        moroccoNote_fr: 'Fréquent chez les poules de basse-cour nourries avec des régimes inappropriés ou gardées dans des environnements stressants.',
        references: [{ text: 'Avian Medicine: Principles and Application, 2020', url: 'https://scholar.google.com/scholar?q=Avian+Medicine+Principles+and+Application+Egg+Binding' }],
        lastReviewed: '2025-04-05',
    },
    {
        id: 31,
        name: 'Campylobacteriosis',
        name_fr: 'Campylobactériose',
        aliases: ['Avian Intestinal Spirochetosis'],
        aliases_fr: ['Spirochétose Intestinale Aviaire'],
        scientificName: 'Campylobacter jejuni, C. coli',
        description: 'A major foodborne zoonotic bacterial infection. Birds are often asymptomatic carriers, posing a public health risk through contaminated meat.',
        description_fr: 'Une infection bactérienne zoonotique d’origine alimentaire majeure. Les oiseaux sont souvent des porteurs asymptomatiques, posant un risque pour la santé publique par la viande contaminée.',
        etiology: 'Bacterial',
        urgency: 'LOW',
        zoonoticRisk: 'HIGH',
        speciesAffected: ['Chickens', 'Turkeys', 'Ducks'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Canards'],
        transmission: 'Fecal-oral route, contaminated water or feed, poor hygiene during processing.',
        transmission_fr: 'Voie fécale-orale, eau ou aliments contaminés, mauvaise hygiène lors de l’abattage.',
        symptoms: ['Often asymptomatic', 'Diarrhea', 'Reduced growth in heavy infections'],
        symptoms_fr: ['Souvent asymptomatique', 'Diarrhée', 'Croissance réduite en cas d’infections massives'],
        lesionsAtNecropsy: ['Enteritis', 'Swollen liver', 'Swollen spleen'],
        lesionsAtNecropsy_fr: ['Entérite', 'Foie enflé', 'Rate enflée'],
        bodySystemAffected: ['Digestive', 'Systemic'],
        bodySystemAffected_fr: ['Digestif', 'Systémique'],
        treatment: 'Antibiotic treatment is controversial due to resistance; focus is on prevention.',
        treatment_fr: 'Le traitement antibiotique est controversé en raison de la résistance ; l’accent est mis sur la prévention.',
        prevention: 'Strict biosecurity, clean water, proper cooking of poultry meat, hygiene during slaughter.',
        prevention_fr: 'Biosécurité stricte, eau propre, cuisson adéquate de la viande de volaille, hygiène lors de l’abattage.',
        differentialDiagnosis: ['Salmonellosis', 'E. coli infection'],
        differentialDiagnosis_fr: ['Salmonellose', 'Infection à E. coli'],
        region: 'Global',
        moroccoNote: 'High prevalence in broiler flocks detected during processing. Public awareness on thorough cooking is key.',
        moroccoNote_fr: 'Prévalence élevée dans les lots de poulets de chair détectée lors de l’abattage. La sensibilisation du public à la cuisson complète est essentielle.',
        references: [
            { text: 'CDC Campylobacter', url: 'https://www.cdc.gov/campylobacter/index.html' },
            { text: 'WOAH Campylobacteriosis', url: 'https://www.woah.org/en/disease/campylobacteriosis/' }
        ],
        lastReviewed: '2025-04-05'
    },
    {
        id: 32,
        name: 'Ornithosis (Psittacosis)',
        name_fr: 'Ornithose (Psittacose)',
        aliases: ['Avian Chlamydiosis', 'Parrot Fever'],
        aliases_fr: ['Chlamydiose Aviaire', 'Fièvre du perroquet'],
        scientificName: 'Chlamydia psittaci',
        description: 'A zoonotic bacterial disease that can cause severe respiratory illness in humans. Birds can be asymptomatic carriers.',
        description_fr: 'Une maladie bactérienne zoonotique pouvant provoquer une maladie respiratoire grave chez l’homme. Les oiseaux peuvent être des porteurs asymptomatiques.',
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        zoonoticRisk: 'HIGH',
        isNotifiableInMorocco: true,
        speciesAffected: ['Turkeys', 'Ducks', 'Pigeons', 'Chickens'],
        speciesAffected_fr: ['Dindes', 'Canards', 'Pigeons', 'Poulets'],
        transmission: 'Inhalation of dust from dried feces, respiratory secretions, or feathers.',
        transmission_fr: 'Inhalation de poussière provenant de fèces séchées, de sécrétions respiratoires ou de plumes.',
        symptoms: ['Lethargy', 'Ruffled feathers', 'Green to yellow diarrhea', 'Nasal discharge', 'Conjunctivitis'],
        symptoms_fr: ['Léthargie', 'Plumes hérissées', 'Diarrhée verte à jaune', 'Écoulement nasal', 'Conjonctivite'],
        lesionsAtNecropsy: ['Enlarged spleen', 'Enlarged liver', 'Fibrinous airsacculitis', 'Pericarditis', 'Peritonitis'],
        lesionsAtNecropsy_fr: ['Rate hypertrophiée', 'Foie hypertrophié', 'Aérosacculite fibrineuse', 'Péricardite', 'Péritonite'],
        bodySystemAffected: ['Respiratory', 'Systemic'],
        bodySystemAffected_fr: ['Respiratoire', 'Systémique'],
        treatment: 'Tetracyclines (e.g., Doxycycline) under veterinary supervision.',
        treatment_fr: 'Tétracyclines (par ex., Doxycycline) sous surveillance vétérinaire.',
        prevention: 'Quarantine new birds, good ventilation, dust control, use of Personal Protective Equipment (PPE).',
        prevention_fr: 'Mettre en quarantaine les nouveaux oiseaux, bonne ventilation, contrôle de la poussière, utilisation d’Équipements de Protection Individuelle (EPI).',
        differentialDiagnosis: ['Mycoplasmosis', 'Fowl Cholera', 'Avian Influenza'],
        differentialDiagnosis_fr: ['Mycoplasmose', 'Choléra aviaire', 'Influenza aviaire'],
        region: 'Global',
        moroccoNote: 'A risk for pigeon keepers and workers in turkey processing plants. PPE is crucial.',
        moroccoNote_fr: 'Un risque pour les éleveurs de pigeons et les travailleurs des abattoirs de dindes. Les EPI sont cruciaux.',
        references: [
            { text: 'CDC Psittacosis', url: 'https://www.cdc.gov/psittacosis/index.html' },
            { text: 'WOAH Manual on Chlamydiosis', url: 'https://www.woah.org/en/what-we-do/standards/codes-and-manuals/terrestrial-manual-online-access/?id=169&L=1&htmfile=chapitre_avian_chlamydiosis.htm' }
        ],
        lastReviewed: '2025-04-05'
    },
    {
        id: 33,
        name: 'Avian Staphylococcosis',
        name_fr: 'Staphylococcose Aviaire',
        aliases: ['Staph Infection', 'Bumblefoot'],
        aliases_fr: ['Infection à staphylocoques', 'Pododermatite'],
        scientificName: 'Staphylococcus aureus (including MRSA strains)',
        description: 'A bacterial infection causing localized (e.g., bumblefoot) or systemic disease. Zoonotic risk is present, especially with antibiotic-resistant strains like MRSA.',
        description_fr: 'Une infection bactérienne provoquant une maladie localisée (par ex. pododermatite) ou systémique. Le risque zoonotique est présent, surtout avec des souches résistantes aux antibiotiques comme le SARM.',
        etiology: 'Bacterial',
        urgency: 'MEDIUM',
        zoonoticRisk: 'MODERATE',
        speciesAffected: ['All poultry', 'Chickens', 'Turkeys'],
        speciesAffected_fr: ['Toutes les volailles', 'Poulets', 'Dindes'],
        transmission: 'Entry through skin wounds, contaminated equipment, poor hygiene.',
        transmission_fr: 'Entrée par des plaies cutanées, équipement contaminé, mauvaise hygiène.',
        symptoms: ['Lameness', 'Swollen joints (arthritis)', 'Swollen footpads (bumblefoot)', 'Reduced mobility'],
        symptoms_fr: ['Boiterie', 'Articulations enflées (arthrite)', 'Coussinets plantaires enflés (pododermatite)', 'Mobilité réduite'],
        lesionsAtNecropsy: ['Arthritis with purulent exudate', 'Osteomyelitis', 'Abscesses in skin', 'Septicemia with organ necrosis'],
        lesionsAtNecropsy_fr: ['Arthrite avec exsudat purulent', 'Ostéomyélite', 'Abcès cutanés', 'Septicémie avec nécrose d’organes'],
        bodySystemAffected: ['Musculoskeletal', 'Integumentary', 'Systemic'],
        bodySystemAffected_fr: ['Musculosquelettique', 'Tégumentaire', 'Systémique'],
        treatment: 'Antibiotics based on sensitivity testing; surgical drainage of abscesses.',
        treatment_fr: 'Antibiotiques basés sur un antibiogramme ; drainage chirurgical des abcès.',
        prevention: 'Good litter management, avoid injuries, sanitation, proper flock density.',
        prevention_fr: 'Bonne gestion de la litière, éviter les blessures, assainissement, densité de peuplement adéquate.',
        differentialDiagnosis: ['Mycoplasma synoviae', 'E. coli infection', 'Fowl Cholera'],
        differentialDiagnosis_fr: ['Mycoplasma synoviae', 'Infection à E. coli', 'Choléra aviaire'],
        region: 'Global',
        moroccoNote: 'Bumblefoot is common in backyard flocks. MRSA has been isolated from commercial poultry, posing an occupational risk.',
        moroccoNote_fr: 'La pododermatite est courante dans les basses-cours. Le SARM a été isolé de volailles commerciales, posant un risque professionnel.',
        references: [
            { text: 'Journal of Applied Microbiology', url: 'https://scholar.google.com/scholar?q=Journal+of+Applied+Microbiology+avian+staphylococcus' },
            { text: 'Avian Pathology', url: 'https://scholar.google.com/scholar?q=Avian+Pathology+staphylococcus' }
        ],
        lastReviewed: '2025-04-05'
    },
    {
        id: 34,
        name: 'Avian Pathogenic E. coli (APEC)',
        name_fr: 'E. coli Pathogène Aviaire (APEC)',
        aliases: ['Colibacillosis'],
        aliases_fr: ['Colibacillose'],
        scientificName: 'Escherichia coli',
        description: 'A common secondary bacterial pathogen causing various diseases in poultry. Certain strains are zoonotic, causing urinary tract infections and other illnesses in humans.',
        description_fr: 'Un pathogène bactérien secondaire courant causant diverses maladies chez la volaille. Certaines souches sont zoonotiques, provoquant des infections urinaires et d’autres maladies chez l’homme.',
        etiology: 'Bacterial',
        urgency: 'HIGH',
        zoonoticRisk: 'MODERATE',
        speciesAffected: ['All poultry', 'Chickens', 'Turkeys'],
        speciesAffected_fr: ['Toutes les volailles', 'Poulets', 'Dindes'],
        transmission: 'Fecal contamination of eggs, inhalation of contaminated dust, poor hygiene, secondary to other infections.',
        transmission_fr: 'Contamination fécale des œufs, inhalation de poussière contaminée, mauvaise hygiène, secondaire à d’autres infections.',
        symptoms: ['Respiratory distress', 'Lethargy', 'Reduced appetite', 'Diarrhea', 'High chick mortality'],
        symptoms_fr: ['Détresse respiratoire', 'Léthargie', 'Appétit réduit', 'Diarrhée', 'Mortalité élevée des poussins'],
        lesionsAtNecropsy: ['Fibrinous airsacculitis', 'Pericarditis', 'Perihepatitis (polyserositis)', 'Salpingitis', 'Omphalitis (yolk sac infection)'],
        lesionsAtNecropsy_fr: ['Aérosacculite fibrineuse', 'Péricardite', 'Périhépatite (polysérite)', 'Salpingite', 'Omphalite (infection du sac vitellin)'],
        bodySystemAffected: ['Respiratory', 'Systemic', 'Reproductive'],
        bodySystemAffected_fr: ['Respiratoire', 'Systémique', 'Reproducteur'],
        treatment: 'Antibiotics based on susceptibility testing; often complicated by resistance.',
        treatment_fr: 'Antibiotiques basés sur un antibiogramme ; souvent compliqué par la résistance.',
        prevention: 'Good ventilation, reduce stress, control primary viral/mycoplasma infections, hatchery sanitation, vaccination.',
        prevention_fr: 'Bonne ventilation, réduire le stress, contrôler les infections virales/mycoplasmiques primaires, hygiène du couvoir, vaccination.',
        differentialDiagnosis: ['Mycoplasmosis', 'Fowl Cholera', 'Salmonellosis'],
        differentialDiagnosis_fr: ['Mycoplasmose', 'Choléra aviaire', 'Salmonellose'],
        region: 'Global',
        moroccoNote: 'A major cause of economic loss, often following Infectious Bronchitis or Newcastle Disease outbreaks.',
        moroccoNote_fr: 'Une cause majeure de pertes économiques, survenant souvent après des épidémies de Bronchite Infectieuse ou de Maladie de Newcastle.',
        references: [
            { text: 'WOAH Colibacillosis', url: 'https://www.woah.org/en/disease/avian-colibacillosis/' },
            { text: 'Avian Diseases Journal', url: 'https://scholar.google.com/scholar?q=Avian+Diseases+Journal+APEC' }
        ],
        lastReviewed: '2025-04-05'
    },
    {
        id: 35,
        name: 'Low Pathogenic Avian Influenza (LPAI)',
        name_fr: 'Influenza Aviaire Faiblement Pathogène (IAFP)',
        aliases: ['LPAI', 'Mild Bird Flu'],
        aliases_fr: ['IAFP', 'Grippe aviaire bénigne'],
        scientificName: 'Influenza A virus (H1-H16, non-H5/H7 or low path H5/H7)',
        description: 'A milder form of avian influenza that typically causes minor respiratory signs or goes unnoticed. However, some LPAI strains (H5/H7) can mutate into Highly Pathogenic Avian Influenza (HPAI), posing a significant threat.',
        description_fr: "Une forme plus bénigne de l'influenza aviaire qui provoque généralement des signes respiratoires mineurs ou passe inaperçue. Cependant, certaines souches d'IAFP (H5/H7) peuvent muter en Influenza Aviaire Hautement Pathogène (IAHP), constituant une menace importante.",
        etiology: 'Viral',
        urgency: 'MEDIUM',
        zoonoticRisk: 'MODERATE',
        isNotifiableInMorocco: true,
        speciesAffected: ['Chickens', 'Turkeys', 'Ducks', 'Geese', 'Wild Birds'],
        speciesAffected_fr: ['Poulets', 'Dindes', 'Canards', 'Oies', 'Oiseaux sauvages'],
        transmission: 'Direct contact with infected birds (feces, nasal secretions), contaminated equipment, and water. Wild waterfowl are the main reservoir.',
        transmission_fr: "Contact direct avec des oiseaux infectés (fèces, sécrétions nasales), équipement et eau contaminés. Les oiseaux d'eau sauvages sont le principal réservoir.",
        symptoms: ['Sneezing', 'Coughing', 'Reduced egg production', 'Depression, ruffled feathers', 'Swollen sinuses (Sinusitis)'],
        symptoms_fr: ['Éternuements', 'Toux', 'Baisse de la production d\'œufs', 'Dépression, plumes hérissées', 'Sinus gonflés (Sinusite)'],
        lesionsAtNecropsy: ['Mild sinusitis with exudate', 'Mild tracheitis', 'Lung congestion', 'Egg peritonitis'],
        lesionsAtNecropsy_fr: ['Sinusite légère avec exsudat', 'Trachéite légère', 'Congestion pulmonaire', 'Péritonite vitelline'],
        bodySystemAffected: ['Respiratory', 'Reproductive', 'Systemic'],
        bodySystemAffected_fr: ['Respiratoire', 'Reproducteur', 'Systémique'],
        treatment: 'Supportive care; antibiotics for secondary bacterial infections. No specific antiviral treatment.',
        treatment_fr: "Soins de soutien ; antibiotiques pour les infections bactériennes secondaires. Pas de traitement antiviral spécifique.",
        prevention: 'Strict biosecurity, preventing contact with wild birds, surveillance. Vaccination may be used in some regions for specific strains (H5/H7). Reporting H5/H7 detections is crucial.',
        prevention_fr: "Biosécurité stricte, éviter le contact avec les oiseaux sauvages, surveillance. La vaccination peut être utilisée dans certaines régions pour des souches spécifiques (H5/H7). La déclaration des détections de H5/H7 est cruciale.",
        differentialDiagnosis: ['Infectious Bronchitis', 'Newcastle Disease (lentogenic)', 'Mycoplasmosis', 'Infectious Coryza'],
        differentialDiagnosis_fr: ['Bronchite Infectieuse', 'Maladie de Newcastle (lentogène)', 'Mycoplasmose', 'Coryza Infectieux'],
        region: 'Morocco, Global',
        moroccoNote: 'Surveillance for H5 and H7 subtypes is active due to the risk of mutation to HPAI. Any detection of these subtypes must be reported to ONSSA immediately.',
        moroccoNote_fr: "La surveillance des sous-types H5 et H7 est active en raison du risque de mutation en IAHP. Toute détection de ces sous-types doit être immédiatement signalée à l'ONSSA.",
        references: [
            { text: 'WOAH – Avian Influenza', url: 'https://www.woah.org/en/disease/avian-influenza/' },
            { text: 'FAO Avian Influenza Resources', url: 'https://www.fao.org/animal-health/en' },
            { text: 'CDC - Avian Influenza', url: 'https://www.cdc.gov/flu/avianflu/index.htm' }
        ],
        lastReviewed: '2025-04-05'
    }
];